version: '2.1'

volumes:
    pihole:
    dnsmasq:

services:
    pihole:
        build: pihole
        privileged: true
        network_mode: host
        volumes:
            - 'pihole:/etc/pihole'
            - 'dnsmasq:/etc/dnsmasq.d'
        dns:
            - '127.0.0.1'
            - '1.1.1.1'

    # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use unbound for upstream DNS
    unbound:
        image: klutchell/unbound:1.9.4
        ports:
            - '5053:5053/udp'

    # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5153 to use cloudflared for upstream DNS
    cloudflared:
        image: klutchell/cloudflared:2019.10.4
        ports:
            - '5153:5053/udp'

    # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5253 to use dnscrypt-proxy for upstream DNS
    dnscrypt-proxy:
        image: klutchell/dnscrypt-proxy:2.0.31
        ports:
            - '5253:5053/udp'
