version: '2.1'

volumes:
    pihole:
    dnsmasq:
    unbound:

services:
    pihole:
        build: pihole
        privileged: true
        network_mode: host
        volumes:
            - 'pihole:/etc/pihole'
            - 'dnsmasq:/etc/dnsmasq.d'
        dns:
            - '127.0.0.1'
            - '1.1.1.1'

    # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use unbound for upstream DNS
    unbound:
        image: klutchell/unbound:arm64v8-1.9.3
        ports:
            - '5053:5053/udp'
        volumes:
            - 'unbound:/opt/unbound/etc/unbound'