version: '2.1'

volumes:
  pihole:
  dnsmasq:

services:
  pihole:
    build: pihole
    privileged: true
    network_mode: host
    volumes:
      - 'pihole:/etc/pihole'
      - 'dnsmasq:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
